cc_library(
    name = "tensorflow",
    hdrs = ["@libtensorflow//:tensorflow_c"],
    visibility = ["//visibility:public"],
    deps = [
        "@libtensorflow//:tensorflow_c",
    ],
)

cc_library(
    name = "tf_lite",
    visibility = ["//visibility:public"],
)
